[2024-11-30T08:58:02.505+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:02.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T08:58:02.511+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:02.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:05.360+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:05.346+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:58:05.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:05.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 2.987 seconds
[2024-11-30T08:58:35.790+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:35.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T08:58:35.795+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:35.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:37.752+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:37.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:58:37.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:58:37.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 2.013 seconds
[2024-11-30T08:59:08.047+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:08.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T08:59:08.058+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:08.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:09.017+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:09.005+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:59:09.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:09.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.021 seconds
[2024-11-30T08:59:40.512+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:40.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T08:59:40.524+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:40.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:42.421+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:42.406+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:59:42.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T08:59:42.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.972 seconds
[2024-11-30T09:00:13.099+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:13.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:00:13.112+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:13.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:14.011+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:13.989+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:00:14.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:14.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.974 seconds
[2024-11-30T09:00:44.490+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:44.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:00:44.502+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:44.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:45.640+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:45.625+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:00:45.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:00:45.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.212 seconds
[2024-11-30T09:01:15.967+0000] {processor.py:161} INFO - Started process (PID=662) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:15.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:01:15.971+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:15.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:18.868+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:18.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:01:18.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:18.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 2.974 seconds
[2024-11-30T09:01:49.217+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:49.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:01:49.222+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:49.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:52.233+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:52.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:01:52.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:01:52.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 3.090 seconds
[2024-11-30T09:02:22.478+0000] {processor.py:161} INFO - Started process (PID=716) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:22.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:02:22.482+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:22.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:23.170+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:23.153+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:02:23.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:23.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.731 seconds
[2024-11-30T09:02:53.598+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:53.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:02:53.608+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:53.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:54.814+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:54.806+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:02:54.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:02:54.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.269 seconds
[2024-11-30T09:03:25.998+0000] {processor.py:161} INFO - Started process (PID=771) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:26.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:03:26.003+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:26.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:27.223+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:27.209+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:03:27.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:27.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.308 seconds
[2024-11-30T09:03:57.997+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:58.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:03:58.006+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:58.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:59.007+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:58.979+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:03:59.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:03:59.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.088 seconds
[2024-11-30T09:04:29.730+0000] {processor.py:161} INFO - Started process (PID=833) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:04:29.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:04:29.736+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:29.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:04:30.522+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:30.505+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:04:30.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:04:30.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.843 seconds
[2024-11-30T09:05:01.289+0000] {processor.py:161} INFO - Started process (PID=864) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:01.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:05:01.298+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:01.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:02.138+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:02.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:05:02.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:02.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.903 seconds
[2024-11-30T09:05:32.855+0000] {processor.py:161} INFO - Started process (PID=897) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:32.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:05:32.864+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:32.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:33.817+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:33.803+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:05:33.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:05:33.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.009 seconds
[2024-11-30T09:06:04.120+0000] {processor.py:161} INFO - Started process (PID=943) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:04.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:06:04.128+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:04.127+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:05.103+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:05.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:06:05.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:05.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.046 seconds
[2024-11-30T09:06:35.697+0000] {processor.py:161} INFO - Started process (PID=967) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:35.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:06:35.713+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:35.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:36.578+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:36.562+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:06:36.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:06:36.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.944 seconds
[2024-11-30T09:07:07.198+0000] {processor.py:161} INFO - Started process (PID=1000) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:07.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:07:07.222+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:07.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:08.138+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:08.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:07:08.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:08.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.012 seconds
[2024-11-30T09:07:38.801+0000] {processor.py:161} INFO - Started process (PID=1027) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:38.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:07:38.812+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:38.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:39.930+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:39.920+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:07:39.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:07:39.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.184 seconds
[2024-11-30T09:08:10.921+0000] {processor.py:161} INFO - Started process (PID=1060) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:10.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:08:10.933+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:10.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:12.344+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:12.319+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:08:12.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:12.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.507 seconds
[2024-11-30T09:08:42.635+0000] {processor.py:161} INFO - Started process (PID=1099) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:42.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:08:42.640+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:42.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:43.333+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:43.320+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:08:43.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:08:43.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.740 seconds
[2024-11-30T09:09:14.108+0000] {processor.py:161} INFO - Started process (PID=1159) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:14.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:09:14.113+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:14.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:15.023+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:15.012+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:09:15.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:15.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.946 seconds
[2024-11-30T09:09:46.059+0000] {processor.py:161} INFO - Started process (PID=1186) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:46.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:09:46.063+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:46.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:46.959+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:46.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:09:46.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:09:46.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.938 seconds
[2024-11-30T09:10:17.219+0000] {processor.py:161} INFO - Started process (PID=1212) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:17.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:10:17.223+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:17.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:17.935+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:17.915+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:10:17.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:17.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.753 seconds
[2024-11-30T09:10:49.115+0000] {processor.py:161} INFO - Started process (PID=1240) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:49.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:10:49.121+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:49.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:49.865+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:49.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:10:49.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:10:49.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.810 seconds
[2024-11-30T09:11:21.248+0000] {processor.py:161} INFO - Started process (PID=1267) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:21.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:11:21.253+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:21.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:22.234+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:22.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:11:22.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:22.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.038 seconds
[2024-11-30T09:11:52.664+0000] {processor.py:161} INFO - Started process (PID=1300) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:52.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:11:52.671+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:52.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:53.547+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:53.535+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:11:53.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:11:53.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 0.939 seconds
[2024-11-30T09:12:23.786+0000] {processor.py:161} INFO - Started process (PID=1333) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:23.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:12:23.794+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:23.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:24.922+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:24.908+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:12:24.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:24.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.198 seconds
[2024-11-30T09:12:55.223+0000] {processor.py:161} INFO - Started process (PID=1358) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:55.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:12:55.228+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:55.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:56.217+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:56.204+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:12:56.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:12:56.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.039 seconds
[2024-11-30T09:13:26.707+0000] {processor.py:161} INFO - Started process (PID=1389) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:13:26.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:13:26.731+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:26.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:13:28.338+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:28.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:13:28.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:13:28.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.685 seconds
[2024-11-30T09:13:59.009+0000] {processor.py:161} INFO - Started process (PID=1416) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:13:59.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:13:59.014+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:59.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:14:00.144+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:00.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:14:00.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:14:00.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.187 seconds
[2024-11-30T09:14:30.743+0000] {processor.py:161} INFO - Started process (PID=1446) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:14:30.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:14:30.756+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:30.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:14:32.365+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:32.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:14:32.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:14:32.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.673 seconds
[2024-11-30T09:15:02.630+0000] {processor.py:161} INFO - Started process (PID=1470) to work on /opt/airflow/dags/src/load_table.py
[2024-11-30T09:15:02.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/load_table.py for tasks to queue
[2024-11-30T09:15:02.641+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:15:02.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:15:03.613+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:15:03.600+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/load_table.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/load_table.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:15:03.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/load_table.py
[2024-11-30T09:15:03.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/load_table.py took 1.037 seconds
